### ISSUE TITLE
Exception when enabling the plugin on M2

### ISSUE THREAD

**Issue by YasirNacak** [SomaZ/Blender_BSP_Importer#34]
Hello,
I am using a MacBook Air with an M2 processor and when I attempt to enable the v0.9.634 of the Addon on Blender 3.6.10 and Blender 4 (latest version as of this date), I get this exception:

```
addon_utils.disable: import_bsp not disabled
addon_utils.disable: import_bsp not disabled
Modules Installed (import_bsp) from '/Users/yasirnacak/Blender Models/import_bsp.zip' into '/Users/yasirnacak/Library/Application Support/Blender/3.6/scripts/addons'
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/Users/yasirnacak/Library/Application Support/Blender/3.6/scripts/addons/import_bsp/__init__.py", line 42, in <module>
    from . import UI
  File "/Users/yasirnacak/Library/Application Support/Blender/3.6/scripts/addons/import_bsp/UI.py", line 21, in <module>
    from . import BspClasses
  File "/Users/yasirnacak/Library/Application Support/Blender/3.6/scripts/addons/import_bsp/BspClasses.py", line 17, in <module>
    from . import QuakeShader
  File "/Users/yasirnacak/Library/Application Support/Blender/3.6/scripts/addons/import_bsp/QuakeShader.py", line 28, in <module>
    from . import QuakeSky
  File "/Users/yasirnacak/Library/Application Support/Blender/3.6/scripts/addons/import_bsp/QuakeSky.py", line 155, in <module>
    shader = gpu.types.GPUShader(vertex_shader, fragment_shader)
Exception: Shader Compile Error, see console for more details
```

**Comment by SomaZ** [comment]
Hi, thanks for reporting the issue. Have you tried using the latest pre-release of the addon instead? 
https://github.com/SomaZ/Blender_BSP_Importer/releases/tag/v0.9.94

If the error still comes up, I need the actual shader compile error. I have no experience with blender on mac, but on linux you have to start blender from the console to get the full log. In windows theres a menu button to open the console post launch.

**Comment by YasirNacak** [comment]
I tested this on the latest pre-release of the addon and I still get this exception
```
WARN (bgl): source/blender/python/generic/bgl.c:2662 BPyInit_bgl: 'bgl' imported without an OpenGL backend. Please update your add-ons to use the 'gpu' module. In Blender 4.0 'bgl' will be removed.
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/Users/yasirnacak/Library/Application Support/Blender/3.6/scripts/addons/import_bsp/__init__.py", line 40, in <module>
    from . import UI
  File "/Users/yasirnacak/Library/Application Support/Blender/3.6/scripts/addons/import_bsp/UI.py", line 41, in <module>
    from . import QuakeSky
  File "/Users/yasirnacak/Library/Application Support/Blender/3.6/scripts/addons/import_bsp/QuakeSky.py", line 159, in <module>
    shader = gpu.types.GPUShader(vertex_shader, fragment_shader)
Exception: Shader Compile Error, see console for more details
```

I am copying this from the console window (which I get by running Blender from the terminal), and there is no additional shader compile errors there.

I have managed to find something online that seems similar to the issue here:
https://blender.stackexchange.com/questions/286919/addon-stopped-working-on-mac-metal-in-v3-5-due-to-shader-compile-error-console

**Comment by SomaZ** [comment]
Oh, thanks for the info. Wasn't aware of a new cross compile interface. I added it in my last commit to the rewrite branch. Can you test it without me making a new release? Should be as easy as downloading the latest files, zip the folder and install this new zip. Would be greatly appreciated.

**Comment by YasirNacak** [comment]
I've pulled the latest commit on the rewrite branch and loaded up the addon. It worked with no problems!
I tried importing some .bsp files I had and they seemed to import fine as well.
If there are any test data you want me to try for import/export, please send them.

**Comment by SomaZ** [comment]
Hm, what games are you testing? I would be interested if creating a equirectangular sky image works fine on import. Quake 3 for an example didn't use those afaik. At least the maps I tested always relied on cloud layers exclusively. They aren't supported in the addon yet.
As an example of a jka map
![equirect_sky_preview](https://github.com/SomaZ/Blender_BSP_Importer/assets/17459161/e9f24e3a-6b5d-4516-a8b1-1ce54cee66a7)

**Comment by YasirNacak** [comment]
I work with Q3 so all I have is my Q3 maps. I don't have unfortunately don't have JKA installed.

**Comment by SomaZ** [comment]
Well, theres free games with skyboxes like OpenArena or Tremulous. Would be nice if you could test like "atcs" from Tremulous, but only if you want to. Also feel free to close the issue if its fixed. Thanks for your help so far. 👍

**Comment by SomaZ** [comment]
Since I haven't heard back, I assume the issue is fixed. Thanks again for reporting it.
