### ISSUE TITLE
bsp not imported (using Blender 4.2.0, BSP Importer v0.9.96-pre)

### ISSUE THREAD

**Issue by Windowsurfer** [SomaZ/Blender_BSP_Importer#41]
**Using:**
Blender 4.2.0
BSP Importer v0.9.96-pre

Happens when trying to import a .bsp format file. Seemingly no data was imported afterwards.

```
Python: Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\import_bsp\UI.py", line 169, in execute
    BlenderBSP.import_bsp_file(import_settings)
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\import_bsp\BlenderBSP.py", line 591, in import_bsp_file
    bsp_file = BSP(VFS, import_settings)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\import_bsp\idtech3lib\BSP.py", line 105, in __init__
    raise Exception(
Exception: BSP format not supported


```

**Comment by SomaZ** [comment]
From what game are you trying to import a bsp file? Just because the extension is the same doesn't mean it's a supported file. That's what the error tries to tell you.
